### ISSUE TITLE
是否存在提供非root下载直接使用的预编译包的可能

### ISSUE THREAD

**Issue by edwinjhlee** [pengjianzhang/jzperf#1]
作者你好，

我觉得这个项目很棒，我想试着集成到 我现在开发的[x-cmd](https://x-cmd.com/pkg/)的pkg下载中。x-cmd的pkg是负责在非root环境下载安装二进制的。举个例子，在x-cmd中，在没有python的环境下可以 `x python` 启动python，而pkg则是负责具体下载python。如果集成了，用户就可以没有安装jzperf下，直接 `x jzperf` 来运行了。

但由于我本人对压力测试领域的理解非常浅薄。所以，我有些疑问想请教一下：

1. jzperf 能否在非root模式下运行
2. 能不能编译成不依赖系统库的形式？这样方便用户可以在非root环境下进行测试。
3. jzperf和dperf是不是在功能上是一致的？

关于2，我想先请教可行性。如果你比较忙，可以先作一个技术预估，或者留些相关文档链接，我们跟进学习和评估一下。

**Comment by pengjianzhang** [comment]
1. 不能
2. 依赖dpdk
3. 目前功能一样，未来不一样

**Comment by edwinjhlee** [comment]
明白 ～
